# Generated by Django 2.0.8 on 2018-08-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180812_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilepage',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
