# Generated by Django 2.0.8 on 2018-08-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('students', '0004_auto_20180812_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('mobile_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comments', wagtail.core.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='StudentsProfileSIndexPage',
            new_name='ClassPage',
        ),
        migrations.RemoveField(
            model_name='studentprofilepage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentprofilepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='StudentProfilePage',
        ),
    ]
